name: Build Samaritan for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o samaritan-windows.exe ./cmd/samaritan

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: samaritan-windows
          path: samaritan-windows.exe
