name: Build for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Windows Binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o sam-windows.exe ./cmd/sam
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam-windows
          path: sam-windows.exe
